//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 23.01.2013 17:28:20
namespace HelloWorld
{
    
    /// <summary>
    /// There are no comments for ewolf2012_RalfEntities in the schema.
    /// </summary>
    public partial class ewolf2012_RalfEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ewolf2012_RalfEntities object using the connection string found in the 'ewolf2012_RalfEntities' section of the application configuration file.
        /// </summary>
        public ewolf2012_RalfEntities() : 
                base("name=ewolf2012_RalfEntities", "ewolf2012_RalfEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ewolf2012_RalfEntities object.
        /// </summary>
        public ewolf2012_RalfEntities(string connectionString) : 
                base(connectionString, "ewolf2012_RalfEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ewolf2012_RalfEntities object.
        /// </summary>
        public ewolf2012_RalfEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ewolf2012_RalfEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for JWEwolf_Debitor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Debitor> JWEwolf_Debitor
        {
            get
            {
                if ((this._JWEwolf_Debitor == null))
                {
                    this._JWEwolf_Debitor = base.CreateQuery<Debitor>("[JWEwolf_Debitor]");
                }
                return this._JWEwolf_Debitor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Debitor> _JWEwolf_Debitor;
        /// <summary>
        /// There are no comments for JWEwolf_Debitor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToJWEwolf_Debitor(Debitor debitor)
        {
            base.AddObject("JWEwolf_Debitor", debitor);
        }
    }
    /// <summary>
    /// There are no comments for ewolf2012_RalfModel.Debitor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// intDebitorId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ewolf2012_RalfModel", Name="Debitor")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Debitor : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Debitor object.
        /// </summary>
        /// <param name="intDebitorId">Initial value of intDebitorId.</param>
        /// <param name="strDebitorNumber">Initial value of strDebitorNumber.</param>
        /// <param name="intPortalId">Initial value of intPortalId.</param>
        /// <param name="xmlDetailsSerialized">Initial value of xmlDetailsSerialized.</param>
        /// <param name="strCreateUser">Initial value of strCreateUser.</param>
        /// <param name="strModifyUser">Initial value of strModifyUser.</param>
        /// <param name="dtmCreateDate">Initial value of dtmCreateDate.</param>
        /// <param name="dtmModifyDate">Initial value of dtmModifyDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Debitor CreateDebitor(int intDebitorId, string strDebitorNumber, int intPortalId, string xmlDetailsSerialized, string strCreateUser, string strModifyUser, global::System.DateTime dtmCreateDate, global::System.DateTime dtmModifyDate)
        {
            Debitor debitor = new Debitor();
            debitor.intDebitorId = intDebitorId;
            debitor.strDebitorNumber = strDebitorNumber;
            debitor.intPortalId = intPortalId;
            debitor.xmlDetailsSerialized = xmlDetailsSerialized;
            debitor.strCreateUser = strCreateUser;
            debitor.strModifyUser = strModifyUser;
            debitor.dtmCreateDate = dtmCreateDate;
            debitor.dtmModifyDate = dtmModifyDate;
            return debitor;
        }
        /// <summary>
        /// There are no comments for property intDebitorId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int intDebitorId
        {
            get
            {
                return this._intDebitorId;
            }
            set
            {
                this.OnintDebitorIdChanging(value);
                this.ReportPropertyChanging("intDebitorId");
                this._intDebitorId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("intDebitorId");
                this.OnintDebitorIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _intDebitorId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintDebitorIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintDebitorIdChanged();
        /// <summary>
        /// There are no comments for property strDebitorNumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string strDebitorNumber
        {
            get
            {
                return this._strDebitorNumber;
            }
            set
            {
                this.OnstrDebitorNumberChanging(value);
                this.ReportPropertyChanging("strDebitorNumber");
                this._strDebitorNumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("strDebitorNumber");
                this.OnstrDebitorNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _strDebitorNumber;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrDebitorNumberChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrDebitorNumberChanged();
        /// <summary>
        /// There are no comments for property intPortalId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int intPortalId
        {
            get
            {
                return this._intPortalId;
            }
            set
            {
                this.OnintPortalIdChanging(value);
                this.ReportPropertyChanging("intPortalId");
                this._intPortalId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("intPortalId");
                this.OnintPortalIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _intPortalId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintPortalIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintPortalIdChanged();
        /// <summary>
        /// There are no comments for property intSalesMediumId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> intSalesMediumId
        {
            get
            {
                return this._intSalesMediumId;
            }
            set
            {
                this.OnintSalesMediumIdChanging(value);
                this.ReportPropertyChanging("intSalesMediumId");
                this._intSalesMediumId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("intSalesMediumId");
                this.OnintSalesMediumIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _intSalesMediumId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintSalesMediumIdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintSalesMediumIdChanged();
        /// <summary>
        /// There are no comments for property intMarketingMediumId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> intMarketingMediumId
        {
            get
            {
                return this._intMarketingMediumId;
            }
            set
            {
                this.OnintMarketingMediumIdChanging(value);
                this.ReportPropertyChanging("intMarketingMediumId");
                this._intMarketingMediumId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("intMarketingMediumId");
                this.OnintMarketingMediumIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _intMarketingMediumId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintMarketingMediumIdChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnintMarketingMediumIdChanged();
        /// <summary>
        /// There are no comments for property xmlDetailsSerialized in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string xmlDetailsSerialized
        {
            get
            {
                return this._xmlDetailsSerialized;
            }
            set
            {
                this.OnxmlDetailsSerializedChanging(value);
                this.ReportPropertyChanging("xmlDetailsSerialized");
                this._xmlDetailsSerialized = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("xmlDetailsSerialized");
                this.OnxmlDetailsSerializedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _xmlDetailsSerialized;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnxmlDetailsSerializedChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnxmlDetailsSerializedChanged();
        /// <summary>
        /// There are no comments for property strCreateUser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string strCreateUser
        {
            get
            {
                return this._strCreateUser;
            }
            set
            {
                this.OnstrCreateUserChanging(value);
                this.ReportPropertyChanging("strCreateUser");
                this._strCreateUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("strCreateUser");
                this.OnstrCreateUserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _strCreateUser;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrCreateUserChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrCreateUserChanged();
        /// <summary>
        /// There are no comments for property strModifyUser in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string strModifyUser
        {
            get
            {
                return this._strModifyUser;
            }
            set
            {
                this.OnstrModifyUserChanging(value);
                this.ReportPropertyChanging("strModifyUser");
                this._strModifyUser = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("strModifyUser");
                this.OnstrModifyUserChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _strModifyUser;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrModifyUserChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnstrModifyUserChanged();
        /// <summary>
        /// There are no comments for property dtmCreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime dtmCreateDate
        {
            get
            {
                return this._dtmCreateDate;
            }
            set
            {
                this.OndtmCreateDateChanging(value);
                this.ReportPropertyChanging("dtmCreateDate");
                this._dtmCreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dtmCreateDate");
                this.OndtmCreateDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _dtmCreateDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtmCreateDateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtmCreateDateChanged();
        /// <summary>
        /// There are no comments for property dtmModifyDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime dtmModifyDate
        {
            get
            {
                return this._dtmModifyDate;
            }
            set
            {
                this.OndtmModifyDateChanging(value);
                this.ReportPropertyChanging("dtmModifyDate");
                this._dtmModifyDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("dtmModifyDate");
                this.OndtmModifyDateChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _dtmModifyDate;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtmModifyDateChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OndtmModifyDateChanged();
    }
}
