#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ewolf2012_Ralf")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJWEwolf_Debitor(JWEwolf_Debitor instance);
    partial void UpdateJWEwolf_Debitor(JWEwolf_Debitor instance);
    partial void DeleteJWEwolf_Debitor(JWEwolf_Debitor instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::LinqToSql.Properties.Settings.Default.ewolf2012_RalfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JWEwolf_Debitor> JWEwolf_Debitors
		{
			get
			{
				return this.GetTable<JWEwolf_Debitor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="jw.JWEwolf_Debitor")]
	public partial class JWEwolf_Debitor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _intDebitorId;
		
		private string _strDebitorNumber;
		
		private int _intPortalId;
		
		private System.Nullable<int> _intSalesMediumId;
		
		private System.Nullable<int> _intMarketingMediumId;
		
		private System.Xml.Linq.XElement _xmlDetailsSerialized;
		
		private string _strCreateUser;
		
		private string _strModifyUser;
		
		private System.DateTime _dtmCreateDate;
		
		private System.DateTime _dtmModifyDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnintDebitorIdChanging(int value);
    partial void OnintDebitorIdChanged();
    partial void OnstrDebitorNumberChanging(string value);
    partial void OnstrDebitorNumberChanged();
    partial void OnintPortalIdChanging(int value);
    partial void OnintPortalIdChanged();
    partial void OnintSalesMediumIdChanging(System.Nullable<int> value);
    partial void OnintSalesMediumIdChanged();
    partial void OnintMarketingMediumIdChanging(System.Nullable<int> value);
    partial void OnintMarketingMediumIdChanged();
    partial void OnxmlDetailsSerializedChanging(System.Xml.Linq.XElement value);
    partial void OnxmlDetailsSerializedChanged();
    partial void OnstrCreateUserChanging(string value);
    partial void OnstrCreateUserChanged();
    partial void OnstrModifyUserChanging(string value);
    partial void OnstrModifyUserChanged();
    partial void OndtmCreateDateChanging(System.DateTime value);
    partial void OndtmCreateDateChanged();
    partial void OndtmModifyDateChanging(System.DateTime value);
    partial void OndtmModifyDateChanged();
    #endregion
		
		public JWEwolf_Debitor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intDebitorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int intDebitorId
		{
			get
			{
				return this._intDebitorId;
			}
			set
			{
				if ((this._intDebitorId != value))
				{
					this.OnintDebitorIdChanging(value);
					this.SendPropertyChanging();
					this._intDebitorId = value;
					this.SendPropertyChanged("intDebitorId");
					this.OnintDebitorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strDebitorNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string strDebitorNumber
		{
			get
			{
				return this._strDebitorNumber;
			}
			set
			{
				if ((this._strDebitorNumber != value))
				{
					this.OnstrDebitorNumberChanging(value);
					this.SendPropertyChanging();
					this._strDebitorNumber = value;
					this.SendPropertyChanged("strDebitorNumber");
					this.OnstrDebitorNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intPortalId", DbType="Int NOT NULL")]
		public int intPortalId
		{
			get
			{
				return this._intPortalId;
			}
			set
			{
				if ((this._intPortalId != value))
				{
					this.OnintPortalIdChanging(value);
					this.SendPropertyChanging();
					this._intPortalId = value;
					this.SendPropertyChanged("intPortalId");
					this.OnintPortalIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intSalesMediumId", DbType="Int")]
		public System.Nullable<int> intSalesMediumId
		{
			get
			{
				return this._intSalesMediumId;
			}
			set
			{
				if ((this._intSalesMediumId != value))
				{
					this.OnintSalesMediumIdChanging(value);
					this.SendPropertyChanging();
					this._intSalesMediumId = value;
					this.SendPropertyChanged("intSalesMediumId");
					this.OnintSalesMediumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intMarketingMediumId", DbType="Int")]
		public System.Nullable<int> intMarketingMediumId
		{
			get
			{
				return this._intMarketingMediumId;
			}
			set
			{
				if ((this._intMarketingMediumId != value))
				{
					this.OnintMarketingMediumIdChanging(value);
					this.SendPropertyChanging();
					this._intMarketingMediumId = value;
					this.SendPropertyChanged("intMarketingMediumId");
					this.OnintMarketingMediumIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xmlDetailsSerialized", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement xmlDetailsSerialized
		{
			get
			{
				return this._xmlDetailsSerialized;
			}
			set
			{
				if ((this._xmlDetailsSerialized != value))
				{
					this.OnxmlDetailsSerializedChanging(value);
					this.SendPropertyChanging();
					this._xmlDetailsSerialized = value;
					this.SendPropertyChanged("xmlDetailsSerialized");
					this.OnxmlDetailsSerializedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strCreateUser", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string strCreateUser
		{
			get
			{
				return this._strCreateUser;
			}
			set
			{
				if ((this._strCreateUser != value))
				{
					this.OnstrCreateUserChanging(value);
					this.SendPropertyChanging();
					this._strCreateUser = value;
					this.SendPropertyChanged("strCreateUser");
					this.OnstrCreateUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strModifyUser", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string strModifyUser
		{
			get
			{
				return this._strModifyUser;
			}
			set
			{
				if ((this._strModifyUser != value))
				{
					this.OnstrModifyUserChanging(value);
					this.SendPropertyChanging();
					this._strModifyUser = value;
					this.SendPropertyChanged("strModifyUser");
					this.OnstrModifyUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtmCreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime dtmCreateDate
		{
			get
			{
				return this._dtmCreateDate;
			}
			set
			{
				if ((this._dtmCreateDate != value))
				{
					this.OndtmCreateDateChanging(value);
					this.SendPropertyChanging();
					this._dtmCreateDate = value;
					this.SendPropertyChanged("dtmCreateDate");
					this.OndtmCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtmModifyDate", DbType="DateTime NOT NULL")]
		public System.DateTime dtmModifyDate
		{
			get
			{
				return this._dtmModifyDate;
			}
			set
			{
				if ((this._dtmModifyDate != value))
				{
					this.OndtmModifyDateChanging(value);
					this.SendPropertyChanging();
					this._dtmModifyDate = value;
					this.SendPropertyChanged("dtmModifyDate");
					this.OndtmModifyDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
